# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# Leave this with the commented command to stop the default tidy from running
#
# We would rather have CI fail and let the developer fix the issue than to have
# goreleaser fix it for us and not know about it.
before:
  hooks:
    #- go mod tidy

builds:
  - binary: bctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    tags:
      - netgo
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s -w -X github.com/mirantiscontainers/boundless-cli/cmd.version=v{{.Version}} -X github.com/mirantiscontainers/boundless-cli/cmd.commit={{.Commit}} -X github.com/mirantiscontainers/boundless-cli/cmd.date={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      bctl_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

# Used during a dev build without a git tag
snapshot:
  name_template: 'bctl-{{ .Version }}-{{.ShortCommit}}'

release:
  # release to the public repository
  github:
    owner: mirantiscontainers
    name: boundless
  name_template: "bctl-v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
