apiVersion: bctl.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: k0s-cluster
spec:
  kubernetes:
    provider: k0s
    version: 1.28.2+k0s.0
    infra:
      hosts:
      - ssh:
          address: 18.208.186.17
          keyPath: ./example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: controller
      - ssh:
          address: 3.239.93.138
          keyPath: ./example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: worker
  components:
    addons:
    - name: example-server
      kind: HelmAddon
      enabled: true
      namespace: default
      chart:
        name: nginx
        repo: https://charts.bitnami.com/bitnami
        version: 15.1.1
        values: |
          "service":
            "type": "ClusterIP"
            "user": $LAIQ_USERNAME
