apiVersion: boundless.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: boundless-cluster
spec:
  kubernetes:
    provider: kind
    config:
      kind: Cluster
      apiVersion: kind.x-k8s.io/v1alpha4
      nodes:
      - role: control-plane
        extraMounts:
        - hostPath: /home/nneisen/code/mke/demo/auth/kind/ssl
          containerPath: /etc/ssl/auth
        extraPortMappings:
        - containerPort: 32000
          hostPort: 32000
        kubeadmConfigPatches:
        - |
          kind: ClusterConfiguration
          apiServer:
            extraArgs:
              oidc-issuer-url: https://dex.example.com:5556
              oidc-client-id: example-app
              # oidc-ca-file: /etc/ssl/auth/ca.pem
              oidc-username-claim: email
              oidc-groups-claim: groups
  components:
    addons:
    - name: example-server
      kind: chart
      enabled: true
      namespace: default
      chart:
        name: nginx
        repo: https://charts.bitnami.com/bitnami
        version: 15.1.1
        values: |
          "service":
            "type": "ClusterIP"
