apiVersion: boundless.mirantis.com/v1alpha1
kind: Addon
metadata:
  name: example-server
spec:
  name: my-example-server
  kind: HelmAddon
  enabled: true
  namespace: default
  chart:
    name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.1.1
    values: |2
      "service":
        "type": "ClusterIP"
---
apiVersion: boundless.mirantis.com/v1alpha1
kind: Addon
metadata:
  name: grafana
spec:
  name: my-grafana
  enabled: true
  kind: HelmAddon
  namespace: monitoring
  chart:
    name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 6.58.7
    values: |
      ingress:
        enabled: true
