apiVersion: boundless.mirantis.com/v1alpha1
kind: Ingress
metadata:
  name: ingress-sample
spec:
  enabled: true
  provider: ingress-nginx
  config: |
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30000
          https: 30001
