apiVersion: boundless.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: k0s-cluster
spec:
  infra:
    hosts:
      - ssh:
          address: 52.91.89.114
          keyPath: example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: controller
      - ssh:
          address: 54.224.178.100
          keyPath: example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: worker
  kubernetes:
    provider: k0s
    version: 1.27.4+k0s.0
    config:
      spec:
        network:
          provider: custom
  components:
    core:
      ingress:
        enabled: true
        provider: kong # ingress-nginx, kong, etc.
        config:
          controller:
            gateway:
              enabled: false
    addons:
    - name: nginx
      enabled: false
      kind: HelmAddon
      namespace: newone
      chart:
        name: nginx
        repo: https://charts.bitnami.com/bitnami
        version: 15.1.1
        values: |
          service:
            type: ClusterIP
    - name: registry
      enabled: true
      kind: HelmAddon
      namespace: registry
      chart:
        name: harbor
        repo: https://helm.goharbor.io
        values: |
          expose:
            type: ingress
            ingress:
              hosts:
                core: registry.mke4.local
                notary: notary.mke4.local
