apiVersion: boundless.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: bop-cluster
spec:
  infra:
    hosts:
      - ssh:
          address: 3.80.73.246
          keyPath: ./example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: controller
      - ssh:
          address: 3.226.255.130
          keyPath: ./example/aws-tf/aws_private.pem
          port: 22
          user: ubuntu
        role: worker
  kubernetes:
    provider: k0s
    version: 1.27.4+k0s.0
  components:
    core:
      ingress:
        enabled: true
        provider: ingress-nginx
        config:
          controller:
            service:
              nodePorts:
                http: 30000
                https: 30001
              type: NodePort
    addons:
      - name: my-grafana
        enabled: true
        kind: HelmAddon
        namespace: monitoring
        chart:
          name: grafana
          repo: https://grafana.github.io/helm-charts
          version: 6.58.7
          values: |
            ingress:
              enabled: true
      - name: example-server
        kind: HelmAddon
        enabled: true
        namespace: default
        chart:
          name: nginx
          repo: https://charts.bitnami.com/bitnami
          version: 15.1.1
          values: |
            service:
              type: ClusterIP
      - name: my-cert-manager
        kind: HelmAddon
        enabled: true
        namespace: default
        chart:
          name: cert-manager
          repo: https://charts.jetstack.io
          version: 1.12.4

     
        
