name: Build Binary

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the binary
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Upload the binary
        if: ${{ github.event_name == 'release' || github.event_name == 'push'}} # release or push to main
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BINARY }}
          retention-days: 1
          path: /bin/${{ env.BINARY }}.tar
