name: Build and Publish to github

on:
  workflow_call:

jobs:
  build-and-publish-dev:
    name: Build and publish dev
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      # This needs to be done first so that the tag is removed in the following steps
      - name: Delete tag and release
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: dev
          github_token: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
          delete_release: true
          repo: mirantiscontainers/boundless-cli

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build dev binaries
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}

      - name: Publish dev binaries
        uses: softprops/action-gh-release@v1
        with:
          name: dev
          tag_name: dev
          body: "This is the dev build that always represents the latest commit on the main branch. These binaries change frequiently and are not meant for production use."
          token: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
          repository: mirantiscontainers/boundless-cli
          files: |
            **/*.tar.gz
            **/*.zip

  build-and-publish-release:
    name: Build and publish release
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

    - name: Load environment
      uses: c-py/action-dotenv-to-setenv@v4
      with:
        env-file: .github/development.env

    - name: Setup Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build and publish release binaries
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: --clean
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}

    - name: Publish binaries to private repo
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
        files: |
          **/*.tar.gz
          **/*.zip
