name: Build

on:
  workflow_call:

jobs:
  linux:
    if: ${{ github.event_name == 'pull_request' }} # only build separate for PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the binary
        env:
          GOOS: linux
          GITHUB_TOKEN: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.21.2 # Last checked, 1.22.0 broke the build arg. Check before upgrading
          args: build --snapshot --single-target --clean

  windows:
    if: ${{ github.event_name == 'pull_request' }} # only build separate for PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the binary
        env:
          GOOS: windows
          GITHUB_TOKEN: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.21.2 # Last checked, 1.22.0 broke the build arg. Check before upgrading
          args: build --snapshot --single-target --clean

  mac:
    if: ${{ github.event_name == 'pull_request' }} # only build separate for PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the binary
        env:
          GOOS: darwin
          GITHUB_TOKEN: ${{ secrets.PAT_CI_DOCKER_EE_MKE }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.21.2 # Last checked, 1.22.0 broke the build arg. Check before upgrading
          args: build --snapshot --single-target --clean
