name: Release

# This makes it so the default token can push to the private releases page
permissions:
  contents: write

on:
  release:
    types: [prereleased]

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
      uses: ./.github/workflows/unit.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  build-and-publish-to-github:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [vet, unit-test, e2e]
    uses: ./.github/workflows/build-and-publish-to-github.yml
    secrets: inherit
