name: Release CLI Binary

on:
  push:
    tags:
      - "*"

jobs:
  build-binaries:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to Public Repository
        uses: softprops/action-gh-release@v1
        with:
          repository: Mirantis/boundless
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
